<a href="https://colab.research.google.com/github/vintagedeek/CICIDS2017/blob/master/cicids2017_best_run.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [112]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

from collections import OrderedDict, namedtuple
from itertools import product
import time
from IPython.display import display, clear_output
import json

import torch 
from torchvision.transforms import Normalize
import torch.nn as nn 
import torch.optim as optim
import torch.nn.functional as F

from scipy.ndimage.interpolation import shift
from PIL import Image

import seaborn as sns
sns.set_style('whitegrid')
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib as mpl
plt.style.use('seaborn-whitegrid')

In [113]:
train_url = 'https://raw.githubusercontent.com/r-dube/CICIDS2017/master/MachineLearningCVE/processed/bal-cicids2017.csv'
df_train = pd.read_csv(train_url)

In [114]:
df_train.head()

    X1        X2  X3  X4   X5  ...         X75          X76       X77       X78  YY
0   53     31065   2   2   68  ...         0.0     0.000000         0         0   0
1  123  67042799   2   2   96  ...  67000000.0     0.000000  67000000  67000000   0
2   53     49637   2   2  180  ...         0.0     0.000000         0         0   0
3   53     48242   1   1   44  ...         0.0     0.000000         0         0   0
4  443  90102413   3   3   18  ...  44998236.5  3288.753639  45000562  44995911   0

[5 rows x 77 columns]

In [115]:
df_train['YY'].value_counts()

0     40000
12     8000
11     8000
10     8000
9      8000
8      8000
7      8000
6      8000
5      8000
4      8000
3      8000
2      8000
1      8000
Name: YY, dtype: int64

In [116]:
df_train.iloc[0:40001]['YY'].value_counts()

0    40000
1        1
Name: YY, dtype: int64

In [117]:
df_train = df_train.iloc[32000:]
df_train = df_train.sample(frac=1).reset_index(drop=True) # Here, specifying drop=True prevents .reset_index from creating a column containing the old index entries.
df_train['YY'].value_counts()
# https://stackoverflow.com/questions/29576430/shuffle-dataframe-rows

12    8000
11    8000
10    8000
9     8000
8     8000
7     8000
6     8000
5     8000
4     8000
3     8000
2     8000
1     8000
0     8000
Name: YY, dtype: int64

In [118]:
df_train.iloc[:, -1]

0          2
1          2
2          6
3         10
4          6
          ..
103995    10
103996    10
103997    12
103998     7
103999     7
Name: YY, Length: 104000, dtype: int64

# Standardization using sklearn
- See below. StandardScaler() standardizes each feature (each column of array).


- Since we fit on the training data only, the mean and standard deviation will only be based on the training data. Not the validation or test data.


- The validation data is standardized using mean/std that came from only the training data (so the validation data hasn't leaked into the training data).This prevents overfitting.


- It also makes sense. Our weights are trained based on a random variable X - mean / std. If we use different mean/std for validation data, we have created a new random variable and our weights do not apply to that random variable.

In [119]:
df_train_copy = df_train[0:83200].copy()
y = df_train_copy['YY']
scaler = preprocessing.StandardScaler()
z = df_train_copy.iloc[:, :-1].values.copy()
train = torch.tensor(scaler.fit_transform(z), dtype=torch.float32)
train_labels = torch.tensor(df_train_copy['YY'].values.copy(), dtype=torch.int64).squeeze()

df_train_copy2 = df_train[83200:].copy()
vy = df_train_copy2['YY']
v = df_train_copy2.iloc[:, :-1].values.copy()
val = torch.tensor(scaler.transform(v), dtype=torch.float32)
val_labels = torch.tensor(df_train_copy2.iloc[:, -1].values.copy()).squeeze()

print(train.shape, train_labels.shape, val.shape, val_labels.shape)

torch.Size([83200, 76]) torch.Size([83200]) torch.Size([20800, 76]) torch.Size([20800])

In [120]:
val_labels

tensor([ 7,  5,  8,  ..., 12,  7,  7])

In [121]:
train_labels[80000:80002]

tensor([ 8, 10])

In [19]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [130]:
class RunBuilder():
    @staticmethod
    def get_runs(params):

        Run = namedtuple('Run', params.keys())

        runs = []
        for v in product(*params.values()):
            runs.append(Run(*v))

        return runs

class RunManager():
    def __init__(self):
        self.epoch_count = 0
        self.epoch_loss = 0
        self.epoch_num_correct = 0
        self.val_correct = 0
        self.epoch_start_time = None
        
        self.run_params = None
        self.run_count = 0
        self.run_data = []
        self.run_start_time = None
        
        self.network = None

       
    def begin_run(self, run, network):
        self.run_start_time = time.time()
        
        self.epoch_count = 0
        self.run_params = run
        self.run_count += 1
        
        self.network = network
        
    def end_run(self):
        self.epoch_count = 0
    
    def begin_epoch(self):
        self.epoch_start_time = time.time()
        self.epoch_count += 1
        self.epoch_loss = 0
        self.epoch_num_correct = 0
        self.val_correct = 0
    
    def end_epoch(self):
        epoch_duration = time.time() - self.epoch_start_time
        run_duration = time.time() - self.run_start_time
        
        loss = self.epoch_loss / len(train)
        train_accuracy = self.epoch_num_correct / len(train)

        val_accuracy = self.val_correct/len(validation_set)

            
        results = OrderedDict()
        results["run"] = self.run_count
        results['epoch'] = self.epoch_count
        results['loss'] = loss
        results['train_accuracy'] = train_accuracy
        results['val_accuracy'] = val_accuracy
        results['epoch duration'] = epoch_duration
        results['run duration'] = run_duration
        for k, v in self.run_params._asdict().items(): results[k] = v
        self.run_data.append(results)
        df = pd.DataFrame.from_dict(self.run_data, orient='columns')
        clear_output(wait=True)
        display(df)
    
    def track_loss(self, loss):
        self.epoch_loss += loss.item() * 10
    
    def track_num_correct(self, preds, labels):
        self.epoch_num_correct += self._get_num_correct(preds, labels)
      
    def track_val_accuracy(self, model):
        with torch.no_grad():
            validation_preds = model(validation_set)
            self.val_correct += validation_preds.argmax(dim=1).eq(validation_labels).sum().item()
   
    @torch.no_grad()
    def _get_num_correct(self, preds, labels):
        return preds.argmax(dim=1).eq(labels).sum().item()
    
    def save(self, fileName): # save in json and csv
        
        pd.DataFrame.from_dict(self.run_data, orient='columns').to_csv(f'{fileName}.csv')
        
        with open(f'{fileName}.json', 'w', encoding='utf-8') as f:
            json.dump(self.run_data, f, ensure_ascii=False, indent=4)

In [136]:
validation_set = val.to(device)
validation_labels = val_labels.to(device)

params = OrderedDict(
    lr = [0.004],
    batch_size = [8],
    device = ['cuda'],
    weight_decay = [0.0])#, 1.0, 10.0])

m = RunManager()
for run in RunBuilder.get_runs(params):

    network = nn.Sequential(
        nn.Linear(in_features=76, out_features=26),
        nn.ReLU(),
        nn.BatchNorm1d(26),
        nn.Linear(in_features=26, out_features=13)).to(device)
    
    mini_batches = [train[k:k + run.batch_size] for k in range(0, train_labels.shape[0], run.batch_size)]
    mini_labels = [train_labels[k:k + run.batch_size] for k in range(0, train_labels.shape[0], run.batch_size)]
    optimizer = optim.Adam(network.parameters(), lr=run.lr, weight_decay=run.weight_decay)
    scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.1)

    m.begin_run(run, network)
    for epoch in range(20):
        m.begin_epoch()
        for b in range(0, len(mini_batches)):
            images = mini_batches[b].to(device)
            labels = mini_labels[b].to(device)
            preds = network(images) # pass batch
            loss = F.cross_entropy(preds, labels) # calculate loss
            optimizer.zero_grad() # zero gradients
            loss.backward() # calculate gradients
            optimizer.step() # update weights

            m.track_loss(loss)
            m.track_num_correct(preds, labels)
        m.track_val_accuracy(network)
        m.end_epoch()
        scheduler.step()
    m.end_run()

pd.DataFrame.from_dict(m.run_data).sort_values('val_accuracy', ascending=False)[0:15]

    run  epoch      loss  ...  batch_size  device  weight_decay
0     1      1  0.374821  ...           8    cuda           0.0
1     1      2  0.243627  ...           8    cuda           0.0
2     1      3  0.215373  ...           8    cuda           0.0
3     1      4  0.198310  ...           8    cuda           0.0
4     1      5  0.184110  ...           8    cuda           0.0
5     1      6  0.178202  ...           8    cuda           0.0
6     1      7  0.175451  ...           8    cuda           0.0
7     1      8  0.171464  ...           8    cuda           0.0
8     1      9  0.167335  ...           8    cuda           0.0
9     1     10  0.163256  ...           8    cuda           0.0
10    1     11  0.135941  ...           8    cuda           0.0
11    1     12  0.130290  ...           8    cuda           0.0
12    1     13  0.128761  ...           8    cuda           0.0
13    1     14  0.127383  ...           8    cuda           0.0
14    1     15  0.126888  ...           8    cuda           0.0
15    1     16  0.125818  ...           8    cuda           0.0
16    1     17  0.125437  ...           8    cuda           0.0
17    1     18  0.124654  ...           8    cuda           0.0
18    1     19  0.124173  ...           8    cuda           0.0
19    1     20  0.123349  ...           8    cuda           0.0
20    1     21  0.120119  ...           8    cuda           0.0
21    1     22  0.119612  ...           8    cuda           0.0
22    1     23  0.119173  ...           8    cuda           0.0
23    1     24  0.119134  ...           8    cuda           0.0
24    1     25  0.118941  ...           8    cuda           0.0
25    1     26  0.118909  ...           8    cuda           0.0
26    1     27  0.118746  ...           8    cuda           0.0
27    1     28  0.118566  ...           8    cuda           0.0
28    1     29  0.118664  ...           8    cuda           0.0
29    1     30  0.118523  ...           8    cuda           0.0
30    1     31  0.117851  ...           8    cuda           0.0
31    1     32  0.117806  ...           8    cuda           0.0
32    1     33  0.117778  ...           8    cuda           0.0
33    1     34  0.117763  ...           8    cuda           0.0
34    1     35  0.117744  ...           8    cuda           0.0

[35 rows x 11 columns]

    run  epoch      loss  ...  batch_size  device  weight_decay
18    1     19  0.124173  ...           8    cuda           0.0
19    1     20  0.123349  ...           8    cuda           0.0
16    1     17  0.125437  ...           8    cuda           0.0
17    1     18  0.124654  ...           8    cuda           0.0
15    1     16  0.125818  ...           8    cuda           0.0
33    1     34  0.117763  ...           8    cuda           0.0
32    1     33  0.117778  ...           8    cuda           0.0
31    1     32  0.117806  ...           8    cuda           0.0
34    1     35  0.117744  ...           8    cuda           0.0
28    1     29  0.118664  ...           8    cuda           0.0
30    1     31  0.117851  ...           8    cuda           0.0
24    1     25  0.118941  ...           8    cuda           0.0
27    1     28  0.118566  ...           8    cuda           0.0
29    1     30  0.118523  ...           8    cuda           0.0
26    1     27  0.118746  ...           8    cuda           0.0

[15 rows x 11 columns]

In [139]:
m.save('cicids_batch_lr_grid_search_validation')

# Best Run
- Val accuracy 97.7837 at epoch 18 (ran for 35, but think 20 epochs better for performance).
- Standardized features, 1 hidden layer (26 neurons)
- Linear, ReLU, BatchNorm1d, Linear
- Cross Entropy Cost Function
- lr=0.004, decaying at 0.5 every 10 epochs
- bs=8
![image.png]()